plugins {
    id 'java'
    id 'application'
}

group = 'ru.skliss'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'ru.skliss.StreamHomework'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('run') {
    standardOutput = System.out
}

tasks.named('jar') {
    manifest {
        attributes 'Main-Class': 'ru.skliss.StreamHomework'
    }
}
